version: '3.1'

#reverse-proxy
#https://dev.to/ishankhare07/nginx-as-reverse-proxy-for-a-flask-app-using-docker-3ajg
services:
    nginx:
        image: nginx:1.16
        container_name: nginx
        depends_on:
            - web
        volumes:
            - ./config_nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - my-network
        ports:
            - 80:80

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: web
        volumes:
            - ./:/opt
        depends_on:
            - redis
        networks:
            my-network:
                aliases:
                    - web-app

    redis:
        image: redis
        container_name: redis
        ports: 
            - 6379:6379
        networks:
            my-network:

networks:
    my-network:




